USE [W_GnBD]
ALTER INDEX ALL ON USERLOGIN
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESS
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESSARGUMENT
REBUILD;
ALTER INDEX ALL ON NOTIFICATIONEMAILSIGNATURE
REBUILD;
ALTER INDEX ALL ON NOTIFICATIONMESSAGE
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESSATTACHMENTS
REBUILD;
ALTER INDEX ALL ON USERAUTHORIZATION
REBUILD;
ALTER INDEX ALL ON TRAAGENT
REBUILD;
ALTER INDEX ALL ON TRACITY
REBUILD;
ALTER INDEX ALL ON TRACONTACT
REBUILD;
ALTER INDEX ALL ON TRACOUNTRY
REBUILD;
ALTER INDEX ALL ON TRAPHOTO
REBUILD;
ALTER INDEX ALL ON TRAPROPERTY
REBUILD;
ALTER INDEX ALL ON TRABROKER
REBUILD;
GO